### ISSUE TITLE
handlers not firing on iOS

### ISSUE THREAD

**Issue by billdami** [hamdiwanis/nativescript-app-tour#16] opened 2019-10-23 19:41 UTC
Testing this on iOS 12.4.1, it appears that none of the tour event handlers are being called. And even putting a breakpoint in the `AppTourDelegate.prototype.showCaseDidDismissWithShowcaseDidTapTarget` method, it appears that it is not being invoked at all. This also causes multi-stop tours to not work, as tapping the target of the first step does not cause the next step to be shown.

**Comment by Omar-Al-Ashi** [comment] 2020-02-19 12:56
I found a workaround for this issue.
After you initialize a tour and pass the stops and handlers, reset the tour and then show it afterward.

ex: 
`this.tour = new AppTour(stops, handlers);
this.tour.reset();
this.tour.show();`

**Comment by erjdriver** [comment] 2020-05-25 00:45
This is not working for me on my iPhone X - running 13.4.1

The workaround seems to work on the simulator.

**Comment by hamdiwanis** [comment] 2020-05-25 16:08
if i had to guess i would say this is a race condition of listening to the tour before its created , would anyone like to help investigate its root cause ?

**Comment by erjdriver** [comment] 2020-05-25 21:47
My project is NS w/ typescript.

I added the tour to my page file on the navigatedTo event. I had

```
navigatedTo()
{
   setTimeout( () =>
{
   const stops: apptourModule.TourStop[] = [...];
    const handlers: apptourModule.TourEvents = {...};

            let tour = new apptourModule.AppTour(stops, handlers);
            
            tour.show();

}, 1000 );
}
```

The above wasn't working - i.e. moving to the next stop. (above pseudo code)

Note I've got `tour` as a local variable.

I then saved `tour` on the page as a static/page variable and then it worked.

**Comment by mreall** [comment] 2020-07-14 22:34
Any updates on this? On iOS I see the first step, but can't move on to the next step. @hamdiwanis, it looks like the MaterialShowcase pod has been updated. Could the newer version possibly fix this issue? I don't know enough about using pods in NativeScript to try it out myself. Thanks for your work on this plugin.

**Comment by mreall** [comment] 2020-07-15 02:52
Combining what @billdami and @erjdriver posted, it's now working for me on iOS.  I'm using nativescript-vue, so here's what I did.
```
<script>
import { AppTour } from "nativescript-app-tour";

export default {
   data() {
      return {
         tour: null,
         stops: [
            { ... },
            { ... }
         ]
      };
   },
   methods: {
      startTutorial() {
         const defaults = { ... };
         this.stops.forEach(stop => stop = Object.assign(stop, defaults));
         this.tour = new AppTour(this.stops, {
            finish: () => { this.$emit('close'); }
         });
         this.tour.reset();
         this.tour.show();
      }
   }
};
</script>
```

**Closed as completed** 2022-07-14 11:24 UTC
