### ISSUE TITLE
Null is not an object

### ISSUE THREAD

**Issue by nericode** [hamdiwanis/nativescript-app-tour#3] opened 2018-09-27 14:32 UTC
The first time the add-on is installed on iOS when clicking the add-on element as a tour, the app dies with the following error: 

`JS ERROR TypeError: null is not an object (evaluating 'this.owner.next')`

**Comment by hamdiwanis** [comment] 2018-09-27 14:58
Hi @NeriCodec  :), could you elaborate more on how to reproduce this error? also, did you try the plugin demo? did it have the same problem?

**Comment by nericode** [comment] 2018-09-27 15:16
@hamdiwanis The first time the plugin is installed and the app is opened in ios and the center of the element that surrounds the tour is clicked, the error happens and the app is closed

**Comment by nericode** [comment] 2018-09-27 15:17
Ther error is here https://github.com/hamdiwanis/nativescript-app-tour/blob/e247007c62311da218bb9e5e4437840340f50c19/src/app-tour.ios.ts#L74

**Comment by hamdiwanis** [comment] 2018-09-27 15:21
I know this is the line making it but the tour always have an owner when you call `new AppTour()`, that's why I could not reproduce the error I made a fresh project and copied tour code from the demo but it worked correctly. that is why I asked if you tried the demo. so if you have time give it a shot and let me know :)

**Comment by hamdiwanis** [comment] 2018-09-27 15:23
Also if you can upload a dummy project to github where i can clone it and try to repruce the error it will be very helpfull.

**Comment by nericode** [comment] 2018-09-27 17:43
@hamdiwanis 
I'm going to try it and I'll tell you

**Comment by hamdiwanis** [comment] 2018-10-10 17:53
hey, @NeriCodec should I close this? :)

**Comment by NeriCodec** [comment] 2018-10-10 18:04
Yes, close this, men...

**Closed as completed** 2018-10-10 21:13 UTC
